RinconVerde/urls.py
from django.contrib import admin
from django.urls import path, include
from Producto import views as producto_views
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Producto/', include('Producto.urls')),
    path('Login/', include('Login.urls')),
    path('cart/', include('cart.urls')),
    path('', RedirectView.as_view(url='/Producto/', permanent=True)),  # Redirect the empty path to /Producto/
    
]

cart/urls.py
# cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/', views.add_to_cart, name='add_to_cart'),
    path('', views.view_cart, name='view_cart'),
    path('payment/', views.payment_view, name='payment'),
    path('invoices/', views.view_invoices, name='view_invoices'),
]

cart/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()

    def __str__(self):
        return self.name

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    session_key = models.CharField(max_length=40)

    def __str__(self):
        return f'{self.quantity} of {self.product.name}'
    
    def total_price(self):
        return self.product.price * self.quantity

class Boleta(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)
    precio_total = models.DecimalField(max_digits=10, decimal_places=2)
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Boleta #{self.id} - {self.nombre}'

class BoletaDetalle(models.Model):
    boleta = models.ForeignKey(Boleta, related_name='detalles', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    session_key = models.CharField(max_length=40)

    def __str__(self):
        return f'{self.cantidad} de {self.product.name} en {self.boleta}'

cart/forms.py
# cart/forms.py
from django import forms
from .models import Product

class AddToCartForm(forms.Form):
    product_id = forms.IntegerField()
    quantity = forms.IntegerField(min_value=1, initial=1)

    def clean_quantity(self):
        product_id = self.cleaned_data.get('product_id')
        quantity = self.cleaned_data['quantity']
        
        try:
            product = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            raise forms.ValidationError("Invalid product.")
        
        if quantity > product.stock:
            raise forms.ValidationError(f"Only {product.stock} units available in stock.")
        
        return quantity

cart/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib import messages
from .models import Product, CartItem, Boleta, BoletaDetalle
from django.db import transaction

def view_invoices(request):
    session_key = request.session.session_key
    
    if not session_key:
        return redirect('index')  # Manejar el caso sin sesión de manera adecuada
    
    # Obtener todas las boletas asociadas a la sesión actual
    boletas = Boleta.objects.filter(detalles__session_key=session_key).distinct()
    
    return render(request, 'cart/view_invoices.html', {'boletas': boletas})

def payment_view(request):
    session_key = request.session.session_key
    
    if not session_key:
        return redirect('cart:view_cart')  # Redirige si no hay sesión activa
    
    cart_items = CartItem.objects.filter(session_key=session_key)
    total_price = sum(item.total_price() for item in cart_items)
    
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        direccion = request.POST.get('direccion')
        telefono = request.POST.get('telefono')
        
        # Utilizamos una transacción para garantizar la consistencia de la base de datos
        with transaction.atomic():
            # Crear la boleta
            boleta = Boleta.objects.create(
                nombre=nombre,
                direccion=direccion,
                telefono=telefono,
                precio_total=total_price,
            )
            
            # Agregar productos y cantidades al detalle de la boleta
            for cart_item in cart_items:
                BoletaDetalle.objects.create(
                    boleta=boleta,
                    product=cart_item.product,
                    cantidad=cart_item.quantity,
                    session_key=session_key
                )
                
                # Actualizar el stock del producto
                product = cart_item.product
                product.stock -= cart_item.quantity
                product.save()
        
            # Limpiar el carrito después de procesar la compra
            CartItem.objects.filter(session_key=session_key).delete()
        
        messages.success(request, 'Compra realizada con éxito. Gracias por su compra!')
        return redirect('cart:view_invoices')  # Redirigir a la vista de las boletas
    
    return render(request, 'cart/payment.html', {'cart_items': cart_items, 'total_price': total_price})


def add_to_cart(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        quantity = int(request.POST.get('quantity', 1))
        
        try:
            product = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            messages.error(request, "Invalid product.")
            return redirect('cart:view_cart')  # Cambia 'producto:index' por la URL de la página de productos en 'producto'

        if quantity > product.stock:
            messages.error(request, f"Only {product.stock} units available in stock.")
            return redirect('cart:view_cart')  # Cambia 'producto:index' por la URL de la página de productos en 'producto'
        
        # Recuperar o crear la sesión
        session_key = request.session.session_key
        if not session_key:
            request.session.create()
            session_key = request.session.session_key
        
        # Verificar si ya existe un item en el carrito para este producto y sesión
        cart_item, created = CartItem.objects.get_or_create(product=product, session_key=session_key)
        
        if not created:
            # Si el item ya existe, actualizamos la cantidad
            cart_item.quantity += quantity
        else:
            # Si es un nuevo item, establecemos la cantidad
            cart_item.quantity = quantity
        
        # Verificar si la cantidad total excede el stock disponible
        if cart_item.quantity > product.stock:
            messages.error(request, f"Only {product.stock} units available in stock.")
            return redirect('cart:view_cart')  # Cambia 'producto:index' por la URL de la página de productos en 'producto'
        
        # Guardar el item del carrito actualizado
        cart_item.save()
        
        messages.success(request, f"{product.name} added to cart.")
        return redirect('cart:view_cart')  # Redirige a la vista 'view_cart' del carrito
        
    else:
        return redirect('cart:view_cart')  # Cambia 'producto:index' por la URL de la página de productos en 'producto'


def view_cart(request):
    session_key = request.session.session_key
    
    # Verificar si hay una sesión activa
    if not session_key:
        return render(request, 'cart/view_cart.html', {'cart_items': []})
    
    # Filtrar los ítems del carrito por la sesión actual
    cart_items = CartItem.objects.filter(session_key=session_key)
    
    if request.method == 'POST':
        # Obtener el ID del carrito y la cantidad a actualizar o eliminar
        cart_item_id = request.POST.get('cart_item_id')
        action = request.POST.get('action')
        
        if action == 'update':
            new_quantity = int(request.POST.get('quantity', 0))
            cart_item = get_object_or_404(CartItem, id=cart_item_id, session_key=session_key)
            product = cart_item.product
            
            # Verificar si la nueva cantidad solicitada excede el stock disponible
            if new_quantity > product.stock:
                messages.error(request, f"Only {product.stock} units available in stock.")
            else:
                cart_item.quantity = new_quantity
                cart_item.save()
        
        elif action == 'delete':
            CartItem.objects.filter(id=cart_item_id, session_key=session_key).delete()
    
    return render(request, 'cart/view_cart.html', {'cart_items': cart_items})

cart/templates/cart/add_to_cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add to Cart</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container mt-5">
        <h1>Añadir al Carrito</h1>
        <form method="post" action="{% url 'cart:add_to_cart' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="product">Selecciona un producto:</label>
                <select name="product_id" id="product" class="form-control">
                    {% for product in products %}
                    <option value="{{ product.id }}">{{ product.name }} - ${{ product.price }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="quantity">Cantidad:</label>
                <input type="number" name="quantity" value="1" min="1" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Agregar al carrito</button>
        </form>
        <a href="{% url 'cart:view_cart' %}" class="btn btn-secondary mt-3">Ver carrito</a>
    </div>
</body>
</html>

cart/templates/cart/payment.html
<!-- cart/view_cart.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Rincon Verde</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  <link href="{% static 'producto/CSS/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/payment.css' %}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap" rel="stylesheet">
  <title>Rincon Verde</title>
</head>
<body>

<!-- Inicio de la barra de navegación -->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <!-- Este es el logo o nombre de la página web -->
  
  <a class="navbar-brand text-white" href="#"><strong>Zen Vibes</strong></a>
  <!-- Este botón aparece cuando la pantalla es pequeña (responsive design) -->
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- Aquí están los enlaces de la barra de navegación -->
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav me-auto">
      <!-- Cada 'li' es un enlace en la barra de navegación -->
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "index" %}"><strong>Inicio</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "brotes" %}"><strong>Hogar</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "arbustos" %}"><strong>Tecnologia</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "sustrato" %}"><strong>Salud y Belleza</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "macetero" %}"><strong>Juguetes</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "nosotros" %}"><strong>Nosotros</strong></a>
      </li>
    </ul>
    <!-- Iconos de usuario y carrito alineados a la derecha -->
    <a href="{% url "login" %}" class="navbar-text text-white ms-auto me-3" id="userIcon">
      <i class="fas fa-user"></i> <span id="usernameDisplay"></span>
    </a>
    <span class="navbar-text text-white me-3" id="cartIcon" data-bs-toggle="modal" style="cursor: pointer;">
      <a href="{% url 'cart:view_cart' %}" class="text-decoration-none text-white">
        <i class="fa fa-shopping-cart"></i>
      </a>
    </span>    
  </div>
</nav>
<!-- Fin de la barra de navegación -->
 
<div class="container mt-5">
  <h1 class="mb-4">Proceder al Pago</h1>
  
  <!-- Mostrar los productos del carrito -->
  <ul class="list-group mb-4">
      {% for item in cart_items %}
      <li class="list-group-item">
          <strong>{{ item.product.name }}</strong> - Cantidad: {{ item.quantity }} - Total: ${{ item.total_price|floatformat:"2" }}
      </li>
      {% endfor %}
      <li class="list-group-item">Total: ${{ total_price }}</li>
  </ul>
  
  <!-- Formulario para ingresar nombre, dirección y teléfono -->
  <form method="post">
      {% csrf_token %}
      <div class="mb-3">
          <label for="nombre" class="form-label">Nombre</label>
          <input type="text" class="form-control" id="nombre" name="nombre" required>
      </div>
      <div class="mb-3">
          <label for="direccion" class="form-label">Dirección</label>
          <input type="text" class="form-control" id="direccion" name="direccion" required>
      </div>
      <div class="mb-3">
          <label for="telefono" class="form-label">Teléfono</label>
          <input type="tel" class="form-control" id="telefono" name="telefono" required>
      </div>
      <button type="submit" class="btn btn-success">Proceder</button>
  </form>
</div>

    <!-- Footer -->
    <footer class="bg-success text-light py-2">
      <div class="container">
        <div class="row">
          <div class="col-md-4 mt-2">
            <h5>Contacto</h5>
            <ul class="list-unstyled text-light">
              <li><i class="fa-solid fa-house me-2"></i>Dirección: Avenida Siempreviva #742, Springfield</i></li>
              <li><i class="fa-solid fa-phone me-2"></i>Teléfono: +123 456 789 </i></li>
              <li><i class="fa-solid fa-envelope me-2"></i>Correo Electrónico: info@zenvibes.com</i></li>
              <li><i class="fa-solid fa-circle-question me-2"></i></i>Ayuda</i></li>
          </ul>
          </div>
          <div class="col-md-4 mt-2">
            <h5>Redes Sociales</h5>
            <ul class="list-unstyled">
              <li><a href="https://www.facebook.com" class="text-light"><i class="fab fa-facebook-f me-2"></i>Facebook</a></li>
              <li><a href="https://www.x.com" class="text-light"><i class="fab fa-twitter me-2"></i>Twitter</a></li>
              <li><a href="https://www.instagram.com" class="text-light"><i class="fab fa-instagram me-2"></i>Instagram</a></li>
            </ul>
          </div>
          <div class="col-md-4 mt-2">
            <h5>Categorias</h5>
            <ul class="list-unstyled text-light">
                <li> Hogar </li>
                <li> Tecnologia </li>
                <li> Salud y Belleza </li>
                <li> Jugetes </li>
            </ul>
        </div>
        </div>
      </div>
    </footer>

  <!-- Bootstrap -->
  <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  <script src="carrito.js"></script>
  <script src="script.js"></script>
  <!-- Javascript -->
  <script src="script.js"></script>
</body>
</html>

cart/templates/cart/view_cart.html
<!-- cart/view_cart.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Rincon Verde</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  <link href="{% static 'producto/CSS/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/view_cart.css' %}" rel="stylesheet">
  
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap" rel="stylesheet">
  
</head>
<body>
<!-- Inicio de la barra de navegación -->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <!-- Este es el logo o nombre de la página web -->
  
  <a class="navbar-brand text-white" href="#"><strong>Zen Vibes</strong></a>
  <!-- Este botón aparece cuando la pantalla es pequeña (responsive design) -->
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- Aquí están los enlaces de la barra de navegación -->
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav me-auto">
      <!-- Cada 'li' es un enlace en la barra de navegación -->
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "index" %}"><strong>Inicio</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "brotes" %}"><strong>Hogar</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "arbustos" %}"><strong>Tecnologia</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "sustrato" %}"><strong>Salud y Belleza</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "macetero" %}"><strong>Juguetes</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url "nosotros" %}"><strong>Nosotros</strong></a>
      </li>
    </ul>
    <!-- Iconos de usuario y carrito alineados a la derecha -->
    <a href="{% url "login" %}" class="navbar-text text-white ms-auto me-3" id="userIcon">
      <i class="fas fa-user"></i> <span id="usernameDisplay"></span>
    </a>
    <span class="navbar-text text-white me-3" id="cartIcon" data-bs-toggle="modal" style="cursor: pointer;">
      <a href="{% url 'cart:view_cart' %}" class="text-decoration-none text-white">
        <i class="fa fa-shopping-cart"></i>
      </a>
    </span>    
  </div>
</nav>
<!-- Fin de la barra de navegación -->

<!-- Carrito -->
<div class="container mt-5">
    <h1 class="mb-4">Carrito de compras</h1>
    <ul class="list-group">
        {% for item in cart_items %}
        <li class="list-group-item">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <strong>{{ item.product.name }}</strong><br>
                    Cantidad:
                    <form method="post" action="{% url 'cart:view_cart' %}">
                        {% csrf_token %}
                        <input type="hidden" name="cart_item_id" value="{{ item.id }}">
                        <input type="hidden" name="action" value="update">
                        <div class="input-group">
                            <input type="number" name="quantity" class="form-control" value="{{ item.quantity }}" min="1" max="{{ item.product.stock }}">
                            <button type="submit" class="btn btn-outline-primary">Actualizar</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-4">
                    Total: ${{ item.total_price|floatformat:"2" }}
                </div>
                <div class="col-md-2">
                    <form method="post" action="{% url 'cart:view_cart' %}">
                        {% csrf_token %}
                        <input type="hidden" name="cart_item_id" value="{{ item.id }}">
                        <input type="hidden" name="action" value="delete">
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'cart:payment' %}" class="btn btn-success mt-auto">Proceder al Pago</a>
</div>
<!-- Fin Carrito-->

    <!-- Footer -->
    <footer class="bg-success text-light py-2">
      <div class="container">
        <div class="row">
          <div class="col-md-4 mt-2">
            <h5>Contacto</h5>
            <ul class="list-unstyled text-light">
              <li><i class="fa-solid fa-house me-2"></i>Dirección: Avenida Siempreviva #742, Springfield</i></li>
              <li><i class="fa-solid fa-phone me-2"></i>Teléfono: +123 456 789 </i></li>
              <li><i class="fa-solid fa-envelope me-2"></i>Correo Electrónico: info@zenvibes.com</i></li>
              <li><i class="fa-solid fa-circle-question me-2"></i></i>Ayuda</i></li>
          </ul>
          </div>
          <div class="col-md-4 mt-2">
            <h5>Redes Sociales</h5>
            <ul class="list-unstyled">
              <li><a href="https://www.facebook.com" class="text-light"><i class="fab fa-facebook-f me-2"></i>Facebook</a></li>
              <li><a href="https://www.x.com" class="text-light"><i class="fab fa-twitter me-2"></i>Twitter</a></li>
              <li><a href="https://www.instagram.com" class="text-light"><i class="fab fa-instagram me-2"></i>Instagram</a></li>
            </ul>
          </div>
          <div class="col-md-4 mt-2">
            <h5>Categorias</h5>
            <ul class="list-unstyled text-light">
                <li> Hogar </li>
                <li> Tecnologia </li>
                <li> Salud y Belleza </li>
                <li> Jugetes </li>
            </ul>
        </div>
        </div>
      </div>
    </footer>

  <!-- Bootstrap -->
  <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  <script src="carrito.js"></script>
  <script src="script.js"></script>
  <!-- Javascript -->
  <script src="script.js"></script>
</body>
</html>